###############################################################################
# 本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                            #
# 非商业性使用 — 不得将此项目及其衍生的项目的源代码和二进制产品用于任何商业和盈利用途#
###############################################################################
Version: 1.4.1
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: False
# 消息推送配置，method 0 为禁用 1 为webApi模式 2 为本地smtp模式 3 为qmsg模式(qq号模式)
# 消息推送配置，method 4 为qmsg模式(qq群模式) method 5 为企业微信模式
notifyOption:
  method: 2
  #############配置1-4选填一个即可
  #############1 webApi配置,根据不同api可能需要自行修改推送模块
  mailApiUrl: ''
  #############2 发信方邮箱账号密码,smtp服务器qq邮箱为smtp.qq.com,163邮箱为smtp.163.com
  smtpOption:
    userName: 'ChiaoCCUT@163.com'
    passWord: 'YCPDOUACEASQCGFB'
    server: 'smtp.163.com'
  #############3 完善qmsgKey即可,需要完善-user字段中qId参数，详见下方例子
  qmsgOption:
    key: ''
    baseUrl: 'https://qmsg.zendee.cn/'
  #############4 企业微信配置
  qywxOption:
    corpid: ''
    corpsecret: ''
    agentid: ''
# 默认不填，如需使用先开通腾讯云OCR服务，再申请API密钥
ocrOption:
  SecretId: 'APIid'
  SecretKey: 'APIkey'
#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user: 
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20214211'
      # password 密码
      password: 'qweasd1234'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '779442425@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy: 
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: 0.jpg
  # 第二个用户配置
  # 以下配置为信息收集
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20191207'
      # password 密码
      password: 'qweasd1234'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '1075268033@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: 2.jpg
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20214216'
      # password 密码
      password: 'yhci29'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '1392290580@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: 1.jpg
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20214271'
      # password 密码
      password: 'mima123456'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '1783579628@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: 3.jpg
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20214248'
      # password 密码
      password: 'fs2205232001'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '3574308916@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: fengshi.jpg
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 1
      # school 学校全称
      schoolName: 长春工业大学
      # username 学号或者工号
      username: '20215036'
      # password 密码
      password: 'liYUEjia2003'
      # 地址信息
      address: '吉林省长春市宽城区地理路'
      notifyOption:
        # method和顶部参数一致，不填默认按照顶部参数执行
        method: 2
        # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
        rcvAcc: '2595103576@qq.com'
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      # lon 经度
      lon: 125.398101
      # lat 纬度
      lat: 44.001899
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
      photo: liyuejia.jpg
#    # 第四个用户配置
#    # 以下配置为查寝
#    # 这里默认仅适配四川信息职业技术学院，其他学校自行修改
#    - user:
#        # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
#        type: 2
#        # school 学校全称
#        schoolName: 四川信息职业技术学院
#        # username 学号或者工号
#        username: ''
#        # password 密码
#        password: ''
#        # 地址信息
#        address: ''
#        notifyOption:
#            # method和顶部参数一致，不填默认按照顶部参数执行
#            # method: 0
#            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
#            rcvAcc: ''
#        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#        # lon 经度
#        lon: 105.895856
#        # lat 纬度
#        lat: 32.424037
#        # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#        abnormalReason: ''
#        # photo 签到照片，不需要可不填，或者直接删除
#        photo: sign.jpg
